// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1jutK4_sMHOZaIN77T6V9HbfpEqNwhy8',
    appId: '1:515114631032:web:56bd02638c140ba2fb128d',
    messagingSenderId: '515114631032',
    projectId: 'myplan-eb9ec',
    authDomain: 'myplan-eb9ec.firebaseapp.com',
    storageBucket: 'myplan-eb9ec.firebasestorage.app',
    measurementId: 'G-1DQTKBLXZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLGKxDC9I-tKFnZCDsqKw5kul4BqIh6Nc',
    appId: '1:515114631032:android:44856b37237867c9fb128d',
    messagingSenderId: '515114631032',
    projectId: 'myplan-eb9ec',
    storageBucket: 'myplan-eb9ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkfYclJoXWp5k11AJVR8pq8f3Zg3lsddU',
    appId: '1:515114631032:ios:f6a4e9d9d3b599bafb128d',
    messagingSenderId: '515114631032',
    projectId: 'myplan-eb9ec',
    storageBucket: 'myplan-eb9ec.firebasestorage.app',
    iosBundleId: 'com.example.myplanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkfYclJoXWp5k11AJVR8pq8f3Zg3lsddU',
    appId: '1:515114631032:ios:f6a4e9d9d3b599bafb128d',
    messagingSenderId: '515114631032',
    projectId: 'myplan-eb9ec',
    storageBucket: 'myplan-eb9ec.firebasestorage.app',
    iosBundleId: 'com.example.myplanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1jutK4_sMHOZaIN77T6V9HbfpEqNwhy8',
    appId: '1:515114631032:web:8f765fba690d68d1fb128d',
    messagingSenderId: '515114631032',
    projectId: 'myplan-eb9ec',
    authDomain: 'myplan-eb9ec.firebaseapp.com',
    storageBucket: 'myplan-eb9ec.firebasestorage.app',
    measurementId: 'G-E1XZJY9LK9',
  );
}
